version: '3.6'
services:
  php-auth:
    build:
      context: ./php-auth
      dockerfile: Dockerfile2
    secrets:
      - secrets.ini
    volumes:
      - ./php-auth:/app
    depends_on:
      - postgres
    environment:
      PDO_DSN:      pgsql:host=postgres;port=5432;dbname=postgres
      PDO_USERNAME: postgres
      PDO_PASSWD:
      SESSION_COOKIE_DOMAIN: .example.com
      SESSION_SAVE_HANDLER:  redis
      SESSION_SAVE_PATH:     redis:6379
      DEVELOPMENT: 0
      PHP_AUTH_TITLE: test

  php-app:
    build: ./php-app
    volumes:
      - ./php-app/public:/var/www/html
    environment:
      SESSION_COOKIE_DOMAIN: .example.com
      SESSION_SAVE_HANDLER:  redis
      SESSION_SAVE_PATH:     redis:6379
      SESSION_SERIALIZE_HANDLER: msgpack

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php-app
      - php-auth

  postgres:
    image: postgres:10-alpine

  redis:
    image: redis:alpine

secrets:
  secrets.ini:
    file: ./secrets.ini

