version: '3.6'
services:
  php-auth:
    build:
      context: ./
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
        COMPOSER_URL:  https://getcomposer.org/download/1.8.6/composer.phar
        COMPOSER_HASH: b66f9b53db72c5117408defe8a1e00515fe749e97ce1b0ae8bdaa6a5a43dd542
    secrets:
      - secrets.ini
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      PDO_DSN:      pgsql:host=postgres;port=5432;dbname=postgres
      PDO_USERNAME: postgres
      PDO_PASSWD:
      DEVELOPMENT: 0
      PHP_AUTH_TITLE: test
      DOCKER: 1

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php-auth

  postgres:
    image: postgres:10-alpine

secrets:
  secrets.ini:
    file: ./secrets.ini

