version: '3.6'
services:
  php-oauth:
    build: ./
    secrets:
      - secrets.ini
    volumes:
      - ./public:/var/www/html
    depends_on:
      - redis
    environment:
      SESSION_COOKIE_DOMAIN: .localhost.test
      SESSION_SAVE_HANDLER:  redis
      SESSION_SAVE_PATH:     redis:6379
      SESSION_SERIALIZE_HANDLER: msgpack

  php-app:
    build: ./app
    volumes:
      - ./app/public:/var/www/html
    depends_on:
      - redis
    environment:
      SESSION_COOKIE_DOMAIN: .localhost.test
      SESSION_SAVE_HANDLER:  redis
      SESSION_SAVE_PATH:     redis:6379
      SESSION_SERIALIZE_HANDLER: msgpack

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - php-app
      - php-oauth

  redis:
    image: redis:alpine
    volumes:
      - ./tmp/redis:/data

secrets:
  secrets.ini:
    file: ./secrets.ini

