version: '3.6'
services:
  php-auth:
    build:
      context: ./
      args:
        COMPOSER_INSTALLER_HASH: 48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5
    secrets:
      - secrets.ini
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      PDO_DSN:      pgsql:host=postgres;port=5432;dbname=postgres
      PDO_USERNAME: postgres
      PDO_PASSWD:
      DEVELOPMENT: 0
      PHP_AUTH_TITLE: test
      DOCKER: 1

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - php-auth

  postgres:
    image: postgres:10-alpine

secrets:
  secrets.ini:
    file: ./secrets.ini

