version: '3.6'
services:
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - php-oauth
  php-oauth:
    build: ./
    secrets:
      - secrets.ini
    volumes:
      - ./public:/var/www/html

secrets:
  secrets.ini:
    file: ./secrets.ini

