version: '3.6'
services:
  php-auth:
    build: ./php-auth
    secrets:
      - secrets.ini
    volumes:
      - ./php-auth/public:/var/www/html
    environment:
      SESSION_COOKIE_DOMAIN: .localhost.test
      SESSION_SAVE_HANDLER:  redis
      SESSION_SAVE_PATH:     redis:6379
      SESSION_SERIALIZE_HANDLER: msgpack

  php-app:
    build: ./php-app
    volumes:
      - ./php-app/public:/var/www/html
    environment:
      SESSION_COOKIE_DOMAIN: .localhost.test
      SESSION_SAVE_HANDLER:  redis
      SESSION_SAVE_PATH:     redis:6379
      SESSION_SERIALIZE_HANDLER: msgpack

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - php-app
      - php-auth

  redis:
    image: redis:alpine
    volumes:
      - ./tmp/redis:/data

secrets:
  secrets.ini:
    file: ./secrets.ini

