version: '3.6'
services:
  php-oauth:
    build: ./
    secrets:
      - secrets.ini
    volumes:
      - ./public:/var/www/html
    depends_on:
      - redis
    environment:
      SESSION_COOKIE_DOMAIN: .localhost.test

  php-app:
    build: ./app
    volumes:
      - ./app/public:/var/www/html
    depends_on:
      - redis
    environment:
      SESSION_COOKIE_DOMAIN: .localhost.test

  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - php-app
      - php-oauth

  redis:
    image: redis:alpine

secrets:
  secrets.ini:
    file: ./secrets.ini

