version: '3.6'
services:
  php-auth:
    build:
      context: ./
      args:
        ALPINE_SERVER: ${ALPINE_SERVER}
        COMPOSER_URL:  https://getcomposer.org/download/1.8.6/composer.phar
        COMPOSER_HASH: b66f9b53db72c5117408defe8a1e00515fe749e97ce1b0ae8bdaa6a5a43dd542
    secrets:
      - secrets.ini
    volumes:
      - ./:/app
    depends_on:
      - mysql
    environment:
      PDO_DSN: mysql:host=mysql;port=3306;dbname=gateway
      PDO_USERNAME: root
      PDO_PASSWORD: root
      DEVELOPMENT: 0
      PHP_AUTH_TITLE: test
      DOCKER: 1
    logging: &logging
      options:
        max-size: "1m"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-auth
    logging: *logging

  mysql:
    image: mysql:5
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gateway
    volumes:
      - mysql:/var/lib/mysql
    logging: *logging

volumes:
  mysql:

secrets:
  secrets.ini:
    file: ./secrets.ini
